import time
from turtle import *
#знак⚠️
fillcolor('yellow')
begin_fill()
forward(100)
left(120)
forward(100)
left(120)
forward(100)
end_fill()
penup()

left(120)
forward(50)
left(90)
forward(15)
dot(5)
forward(10)
width(3)
pendown()
forward(40)
penup()
goto(0,-20)
write("Закройте окно")
done()

#консольная часть
print("Запустить сканирование вашего бобофона?")
input("Нажмите клавишу ENTER для запуска")
time.sleep(1)
print("‼️Сканирование вашего бобофона...")
time.sleep(4)
print("СКАНИРОВАНИЕ ВАШЕГО БОБОФОНА📱 ПРОЯВИЛО ТАКИЕ РЕЗУЛЬТАТЫ:")
print("ОБНАРУЖЕНО 100+ УГРОЗ😳:")
print("24 ОСИНЫХ ГНЕЗДА🐝🐝🐝")
print("31 БЕС👹")
print("50+ БОБОСОВ🦉🦉🦉")
print("ВЫКИНЬТЕ УСТРОЙСТВО В ОКНО 📳📳")
input("НАЖМИТЕ ENTER ЧТОБ ЗАКРЫТЬ ОКОЯНЫЙ АНТИВИРУС🦠❌")